### ISSUE TITLE
Phred quality scores affected by plotting

### ISSUE THREAD

**Issue by GeoMicroSoares** [conchoecia/pauvre#21]
Hello there,

First of all, thanks for this piece of software! Love the summaries and how good the plots look!

I've been having issues with this old dataset I'm analysing though. It has been filtered with fast5-to-fastq (https://github.com/rrwick/Fast5-to-Fastq) to hold only reads with mean Phred scores > 9. However, plotting with pauvre gets me this:

![imagem1](https://user-images.githubusercontent.com/14272488/31544170-6f3eedfa-b011-11e7-911e-058246e8828f.png)

Trying to check if the filtering script was to blame, I used NanoPlot (https://github.com/wdecoster/NanoPlot) to plot the same files and got this:
![bp_v1_qf9_nanoplot](https://user-images.githubusercontent.com/14272488/31544222-a3370f8e-b011-11e7-8320-681a27c1a9aa.png)
Meaning it's a matter of plotting. Funnily enough, using NanoPlot's option --loglength to log read lenghts when plotting I got an approximation at what pauvre is currently plotting:
![bp_v1_qf9_nanoplot_log](https://user-images.githubusercontent.com/14272488/31544258-cf6c11d0-b011-11e7-9604-f4e66570b770.png)

Any tips to get over this? Really wanted to use pauvre to generate my manuscript's figures...
Thanks!

**Comment by conchoecia** [comment]
Hi @GeoMicroSoares, thanks for using `pauvre` and submitting your issue. I wonder what version of `pauvre` you are using? I previously was calculating (and plotting) the error rates incorrectly, but have since corrected it to use the arithmetic mean, like ONT and probably the `fast5tofastq` tool use.

Since it looks like a relatively small `.fastq` file, I would be happy to try to work with your data directly. I notice that the `Number of Reads` axis is also messed up for some reason...

**Comment by GeoMicroSoares** [comment]
Hey again @conchoecia , thanks for the tips! Tried re-installing the software (now running version 0.1.4) but am now getting the following error testing the version:
```pauvre marginplot -f my.fastq -o test.png -n```

/usr/local/lib/python3.4/dist-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.4/dist-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/usr/local/bin/pauvre", line 9, in <module>
    load_entry_point('pauvre==0.1.4', 'console_scripts', 'pauvre')()
  File "/usr/local/lib/python3.4/dist-packages/pauvre/pauvre_main.py", line 297, in main
    args.func(parser, args)
  File "/usr/local/lib/python3.4/dist-packages/pauvre/pauvre_main.py", line 57, in run_subtool
    submodule.run(args)
  File "/usr/local/lib/python3.4/dist-packages/pauvre/marginplot.py", line 370, in run
    margin_plot(args)
  File "/usr/local/lib/python3.4/dist-packages/pauvre/marginplot.py", line 185, in margin_plot
    stats(args.fastq, read_lengths, read_mean_quals)
  File "/usr/local/lib/python3.4/dist-packages/pauvre/stats.py", line 125, in stats
    print_string += "minLen: {}\n".format(min(these_lengths))
ValueError: min() arg is an empty sequence

Any tips? argparse is installed as a module in python3.

Sorry but data is quite sensitive so would love to troubleshoot this command here but can't exactly share it :)
Thanks!

**Comment by GeoMicroSoares** [comment]
Hi again @conchoecia , just to let you know I'm now running version 0.1.6 and error still occurs running the same command.

```
Traceback (most recent call last):
  File "/usr/local/bin/pauvre", line 11, in <module>
    load_entry_point('pauvre==0.1.6', 'console_scripts', 'pauvre')()
  File "/usr/local/lib/python3.4/dist-packages/pauvre/pauvre_main.py", line 355, in main
    args.func(parser, args)
  File "/usr/local/lib/python3.4/dist-packages/pauvre/pauvre_main.py", line 58, in run_subtool
    submodule.run(args)
  File "/usr/local/lib/python3.4/dist-packages/pauvre/marginplot.py", line 370, in run
    margin_plot(args)
  File "/usr/local/lib/python3.4/dist-packages/pauvre/marginplot.py", line 185, in margin_plot
    stats(args.fastq, read_lengths, read_mean_quals)
  File "/usr/local/lib/python3.4/dist-packages/pauvre/stats.py", line 154, in stats
    for this_bin in range(current_val, (np.ceil(maxLen/tss) * tss) + tss, tss):
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```


And same error occurs with numpy version 1.12.1.

Thanks!

**Comment by wdecoster** [comment]
I apologise for hijacking this thread, but did you use a recent version of NanoPlot for this? The x-axis on the log transformed plot doesn't look as it should.

**Comment by GeoMicroSoares** [comment]
@wdecoster version 0.18. It doesn't at all, at this point I'm wondering if my .fastq is the one to blame for all this... Is there a way to tweak bin sizes in NanoPlot? That would help me with all this.

**Comment by wdecoster** [comment]
That's currently not possible, I can look at that. After this I'll leave this thread to be about Pauvre, but it would be great if you could open an issue for NanoPlot, preferentially including the log file.

Your fastq shouldn't affect the outcome - it should theoretically just work and I would like to figure out why it doesn't.

**Comment by conchoecia** [comment]
@GeoMicroSoares, thank you for your patience! I fixed the error that ends with `ValueError: min() arg is an empty sequence`. You can get the latest version by upgrading with `pip`. In the meantime I will try to replicate the plotting issue with some of my data.

Would you mind sending the quality scores from your data? That anonymizes the sequences and I can still troubleshoot why the plot looks off. If you would like to do that, you can run your fastq file like this -> `cat yourfile.fastq | awk '{if(NR%4==0) print length($0)"\t"$0}' > lenqual.tsv` or a gzipped fastq file like this -> `zcat yourfile.fastq.gz | awk '{if(NR%4==0) print length($0)"\t"$0}' > lenqual.tsv`. If you're ok with that, you can email me at dts@ucsc.edu with the file or a link to download.

**Comment by conchoecia** [comment]
@wdecoster @mebbert, it looks like the error that @GeoMicroSoares is reporting is due to @rrwick's package calculating the geometric mean of the quality scores rather than the arithmetic mean. The code that is calculating the geometric mean is [here](https://github.com/rrwick/Fast5-to-Fastq/blob/master/fastq_to_fastq.py#L128)

See #16 for a little bit of background on why we use the arithmetic mean rather than the geometric mean for calculating mean Q scores. @wdecoster also has a nice blog post about it [here](https://gigabaseorgigabyte.wordpress.com/2017/06/26/averaging-basecall-quality-scores-the-right-way/).

Basically, since Q-scores are logarithmic, averaging them directly (geometric mean) inflates the apparent quality score of the read. Instead, one must convert the phred scores to error rate, calculate the error rate mean, then convert that value back to Q-score. Albacore uses the arithmetic mean when reporting mean quality score.

My suggestion to move forward is that I add an option to `pauvre marginplot` to filter out reads before plotting. For example, I could code up a `--min_read_quality 9` option and the plot will only depict reads with an arithmetic mean greater than 9. In this case you would use your entire unfiltered `.fastq(.gz)` file. Let me know if that would be useful to you, @GeoMicroSoares !

**Comment by GeoMicroSoares** [comment]
Glad to know this has a solution and may be a good problem to solve!

@conchoecia that would be ideal yep! Thanks so much!

**Comment by rrwick** [comment]
I was too late to this one - you guys already figured it out: the [Fast5-to-Fastq](https://github.com/rrwick/Fast5-to-Fastq) script calculates mean quality poorly.

I've since written [Filtlong](https://github.com/rrwick/Filtlong) which I'd recommend over that previous tool. Filtlong does mean quality in the more sensible way @conchoecia described: first converting quality scores to probably of being correct, and then getting the arithmetic mean of that value.

However, note that Filtlong doesn't convert mean quality back to a Phred score, but rather leaves it as a probability (expressed as a percent, 0 to 100). E.g. use `--min_mean_q 90`, not `--min_mean_q 10`.

Ryan

**Comment by conchoecia** [comment]
Thanks for your input, @rrwick. I was wondering if you were using arithmetic or geometric mean in your ONT basecalling results repo. 

@GeoMicroSoares, I have made the changes that I described in the latest version (v0.1.81). You can update with `pip3` and it should work. Check out the README for instructions on how to perform the filtering (filter reads with `--filt_minqual`, change the plotting window with `--plot_minqual`). I gave options for both so that you can choose whether to have a little blank space in the plotting window, or to just plot a specific region without filtering. Here's a quick screenshot of what I mean (also in the README).

![test4](https://user-images.githubusercontent.com/3123273/31735095-a776ec12-b3f5-11e7-934d-e942af9800ee.png)

Cheers,
Darrin

**Comment by rrwick** [comment]
For the [basecalling comparison](https://github.com/rrwick/Basecalling-comparison) I ignored the fastq Phred scores. The read identity values there are taken directly from aligning reads to the hybrid-assembled reference. There I define identity like BLAST does: # of matching bases / total # of bases in alignment.

Ryan

**Comment by GeoMicroSoares** [comment]
@conchoecia works nicely with my fastq.'s except for one of them with two huge outlier probably failed reads.

Error it's giving out following the length + meanQual output:
```
[1766 rows x 2 columns]
length >= 0 and meanQual >= 0
Traceback (most recent call last):
  File "/usr/local/bin/pauvre", line 11, in <module>
    load_entry_point('pauvre==0.1.81', 'console_scripts', 'pauvre')()
  File "/usr/local/lib/python3.4/dist-packages/pauvre/pauvre_main.py", line 386, in main
    args.func(parser, args)
  File "/usr/local/lib/python3.4/dist-packages/pauvre/pauvre_main.py", line 58, in run_subtool
    submodule.run(args)
  File "/usr/local/lib/python3.4/dist-packages/pauvre/marginplot.py", line 370, in run
    margin_plot(args)
  File "/usr/local/lib/python3.4/dist-packages/pauvre/marginplot.py", line 187, in margin_plot
    stats(args.fastq, read_lengths, read_mean_quals, False)
  File "/usr/local/lib/python3.4/dist-packages/pauvre/stats.py", line 166, in stats
    first_index_gt_maxLen = next(i for i,v in enumerate(lengthBinList) if v > maxLen) + 1
StopIteration
```
Here's the file, anonymized with @wdecoster's new tool [fastq-anonymous](https://github.com/wdecoster/fastq-anonymous):
[anonymous_reads.zip](https://github.com/conchoecia/pauvre/files/1397739/anonymous_reads.zip)

**Comment by conchoecia** [comment]
Thanks @rrwick, I am interested in running your same analysis on some of my critters. I'll let you know if I can't figure out how to do it from your repo!

@GeoMicroSoares, I just pushed https://github.com/conchoecia/pauvre/commit/b95075e19f357bd9f45f8ab9e01ac10567807ea2 which fixes the problem you described. You can update with `pip3` like before. Some of these errors are because I haven't been writing proper tests for my programs. 😉

I'm going to reopen this for a week, please let me know if you have further trouble.

**Comment by GeoMicroSoares** [comment]
@conchoecia v0.1.82 now working nicely! Thanks for all this!
Can you just share how reads are now selected out of the plot by default? 
Also, would be nice if the marginplot output could have a little summary dedicated to the reads left out as reading the cumulative view can be a bit confusing. :)

**Comment by conchoecia** [comment]
@GeoMicroSoares I made the data table summaries in 5b3a2d73f054c87ea6568e58b3c5cb12729eafc2 (v0.1.83) show only information for the reads remaining after filtering.
